### PR TITLE
Add one more important quality

### PR DESCRIPTION
**Pull request by joaojeronimo**

### CODE REVIEW

**Comment by nfcampos** [comment]
I agree with this addition but it'd be clearer if we could have an example of something that promotes good coding practices, no?

**Comment by joaojeronimo** [comment]
Very good point, good coding practices is very subjective and open to interpretation. But it's also a broad topic and I can't give enough examples to cover everything :(

**Comment by nfcampos** [comment]
I guess that's the thing, good coding practices is almost too broad to be useful, eg. IMO something that is more batteries-included (like hapi) promotes better coding practices than something more DIY (like express) because it promotes consistency, but this is only a small part of *good coding practices*. So perhaps it's be better to have 1 or 2 bullet points with the specific good coding practices we have in mind?

**Comment by joaojeronimo** [comment]
It's certainly a topic worth expanding, I'll start a list and hope people add more to it.

**Comment by tomgco** [comment]
> I guess that's the thing, good coding practices is almost too broad to be useful, eg. IMO something that is more batteries-included (like hapi) promotes better coding practices than something more DIY (like express) because it promotes consistency, but this is only a small part of good coding practices. So perhaps it's be better to have 1 or 2 bullet points with the specific good coding practices we have in mind?

I think we can keep it vague enough so that it is down to the issue to explain why it promotes good coding practises, anything more could make the README too explicit.

**Review by tomgco — APPROVED** [review]

**Comment by joaojeronimo** [comment]
So how do we move with this ? Do I close it ? Do I put it on the javascript file (that came about with #3) ? Do I leave it ambiguous ?

**Comment by nfcampos** [comment]
after this last commit i'm happy with this so i say this should be merged, this is general enough that it should be in the readme i think

**Comment by nfcampos** [comment]
btw, i can't merge or approve PRs here

**Comment by joaojeronimo** [comment]
@nfcampos you need to be added to the Team group, just a sec...

**Pull request merged**
